version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ts-loader
    versions:
    - 8.0.14
    - 8.0.15
    - 8.0.16
    - 8.0.17
    - 8.0.18
    - 8.1.0
    - 9.0.0
    - 9.0.2
    - 9.1.0
  - dependency-name: ws
    versions:
    - 7.4.2
    - 7.4.3
    - 7.4.4
  - dependency-name: ts-jest
    versions:
    - 26.4.4
    - 26.5.0
    - 26.5.1
    - 26.5.2
    - 26.5.3
    - 26.5.4
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.21
    - 26.0.22
  - dependency-name: react-native
    versions:
    - 0.63.4
  - dependency-name: react-redux
    versions:
    - 7.2.2
    - 7.2.3
